{% set version = "4.10.3" %}
{% set menuinst_version = "1.4.17" %}
{% set constructor_version = "3.2.1" %}
{% set python_version = "3.7.8" %}

package:
  name: conda-standalone
  version: {{ version }}

source:
  - path: ./
  - url: https://github.com/conda/conda/archive/{{ version }}.tar.gz
    sha256: 9e83bb20a6b9adc0bd7abccaa4738a71dc04e19a42dc51ad543539c15b2c941a
    folder: conda_src
    patches:
      - conda_patches/0001-Rename-and-replace-entrypoint-stub-exe.patch
      - conda_patches/0002-Manipulate-PATH-directly-instead-of-_call_ing-conda.patch

  - url: https://github.com/conda/menuinst/archive/{{ menuinst_version }}.tar.gz
    sha256: 143bc78efbbe9e34698df3d40f20576ccd9b62a199ebfff83cc5515049f70090
    folder: menuinst_src
    patches:
      - menuinst_patches/0001-Do-not-assume-menuinst-wants-to-operate-on-sys.prefi.patch
      - menuinst_patches/0002-Allow-menuinst-to-operate-on-non-base-prefix-by-addi.patch

  - url: https://github.com/conda/constructor/archive/{{ constructor_version }}.tar.gz  # [win]
    sha256: 666e3be5e6165107d7198d2753e7af6941e7f82d3bef6fc0cc98ec03310c2e01  # [win]
    folder: constructor  # [win]
    patches:
      - constructor_patches/0001-Pass-root_prefix-to-menuinst.install-to-be-used-by-c.patch  # [win]

build:
  number: 1
  ignore_run_exports:
    - '*'

requirements:
  build:
    - pyinstaller
    - python ={{ python_version }}
    - conda ={{ version }}
    - conda-package-handling >=1.6

test:
  commands:
    - ${PREFIX}/standalone_conda/conda.exe -V    # [unix]
    - ${PREFIX}/standalone_conda/conda.exe create -y -p ./env_test zlib tqdm    # [unix]
    - '%PREFIX%\standalone_conda\conda.exe -V'    # [win]
    - '%PREFIX%\standalone_conda\conda.exe create -y -p env_test zlib tqdm'    # [win]

about:
  home: https://github.com/AnacondaRecipes/conda-standalone-feedstock
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Entry point and dependency collection for PyInstaller-based standalone conda.

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - forrestwaters
    - nehaljwani
