{% set version = "4.9.2" %}
{% set menuinst_version = "1.4.16" %}
{% set constructor_version = "3.1.0" %}
{% set python_version = "3.7.8" %}

package:
  name: conda-standalone
  version: {{ version }}

source:
  - path: ./
  - url: https://github.com/conda/conda/archive/{{ version }}.tar.gz
    sha256: d7f946e5c770e45da8961323ca96399bf1a881eb68bbaecc7cb1e249f5c86d54
    folder: conda_src
    patches:
      - conda_patches/0001-Rename-and-replace-entrypoint-stub-exe.patch
      - conda_patches/0002-Manipulate-PATH-directly-instead-of-_call_ing-conda.patch

  - url: https://github.com/ContinuumIO/menuinst/archive/{{ menuinst_version }}.tar.gz
    sha256: c9ad6e225c2831656bac35b71ac1c8c3f82f08ba8da9718dfb3708485bbccc44
    folder: menuinst_src
    patches:
      - menuinst_patches/0001-Do-not-assume-menuinst-wants-to-operate-on-sys.prefi.patch
      - menuinst_patches/0002-Allow-menuinst-to-operate-on-non-base-prefix.patch

  - url: https://github.com/conda/constructor/archive/{{ constructor_version }}.tar.gz  # [win]
    sha256: 13926446679d1e01c6700c3315916536fe57b461fca0e06fbe32eab9e1ba3657  # [win]
    folder: constructor  # [win]

build:
  number: 1

requirements:
  build:
    - pyinstaller
    - python ={{ python_version }}
    - conda ={{ version }}
    - conda-package-handling >=1.6

test:
  commands:
    - "${PREFIX}/standalone_conda/conda.exe -V"  # [unix]
    - "${PREFIX}/standalone_conda/conda.exe create -y -p ./env_test zlib tqdm"  # [unix]
    - "%PREFIX%\\standalone_conda\\conda.exe -V"  # [win]
    - "%PREFIX%\\standalone_conda\\conda.exe create -y -p env_test zlib tqdm"  # [win]

about:
  home: https://github.com/AnacondaRecipes/conda-standalone-feedstock
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Entry point and dependency collection for PyInstaller-based standalone conda.'

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - forrestwaters
    - nehaljwani
